for brew in /opt/homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/brew; do
  if [[ -x $brew ]]; then
    eval "$($brew shellenv zsh)"
    break
  fi
done
unset brew

export PATH="$PATH:$HOME/.local/bin"
